### ISSUE TITLE
BOM and Schematic Differ

### ISSUE THREAD

**Issue by tonyc770** [pra22/GC-01-Geiger-Counter#4]
In the BOM it lists a 10M, and 6.2M resistors, but they are not shown in the schematic.
The schematic shows 3, 100K and a 1K resistors, but not in BOM.

**Comment by pra22** [comment]
The 10M and 6.2M resistors are for testing, and are not needed for the project. The new list shown in the Instructables is correct. I already had the 330, 100K and 1K resistors, which is why they're not in my order list.
